image: node:9

pages:
  depedencies:
    - now
  artifacts:
    paths:
    - public

now:
  script:
  - npm install --unsafe-perm now
  - yarn run deploy-ci
  artifacts:
    paths:
    - public
  cache:
    paths:
    - node_modules
  only:
  - master