image: node:9

stages:
  - build
  - deploy

build:
  stage: build
  script:
  - yarn && yarn run build
  artifacts:
    paths:
    - public
    - node_modules
  cache:
    paths:
    - node_modules
    - .cache
    - public
  only:
  - master

pages:
  stage: deploy
  dependencies:
    - build
  script:
  - echo 'done!'
  artifacts:
    paths:
    - public
  only:
  - master

now:
  stage: deploy
  dependencies:
    - build
  script:
  - npm install --unsafe-perm now
  - yarn run deploy-ci
  only:
  - master