image: node:9
stages:
- build
- audit

pages:
  stage: build
  script:
  - yarn
  - yarn build
  artifacts:
    paths:
    - public
  cache:
    paths:
    - node_modules
    - .cache
    - public
  only:
  - master

audit:
  image: 
    name: thecreazy/siteaudit:1.1.4
    entrypoint: ['']
  stage: audit
  variables:
    SITEAUDIT_URL: "https://master.silvietta.n2.caffeina.host/"
  script:
    - echo "started siteaudit"
    - /usr/local/bin/siteaudit ${SITEAUDIT_URL} --headless
  artifacts:
    paths:
    - output