image: node:9
stages:
- build
- test

pages:
  stage: build
  script:
  - npm install -g --unsafe-perm now
  - yarn
  - yarn build
  artifacts:
    paths:
    - public
  cache:
    paths:
    - node_modules
    - .cache
    - public
  only:
  - master

now:
  stage: build
  script:
  - npm install -g --unsafe-perm now
  - yarn run deploy-ci
  artifacts:
    paths:
    - public
  cache:
    paths:
    - node_modules
    - .cache
    - public
  only:
  - master

lighthouse:
  stage: test
  script:
  - npx lighthouse https://victormagalhaes.codes/ --output-path=./report.html --save-assets
  artifacts:
    untracked: true