image: node:9
stages:
- build
- deploy

pages:
  stage: build
  script:
  - yarn
  - yarn build
  artifacts:
    paths:
    - public
  cache:
    paths:
    - node_modules
    - .cache
    - public

now:
  stage: deploy
  dependencies:
  - pages
  script:
  - npm install -g --unsafe-perm now
  - yarn run deploy-ci
  only:
  - master