image: node:9
stages:
- build

pages:
  stage: build
  script:
  - yarn
  - yarn build
  artifacts:
    paths:
    - public
  cache:
    paths:
    - node_modules
    - .cache
    - public
  only:
  - master
