# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

test:
  script:
  - hugo -t crisp
  except:
  - master

pages:
  script:
  - hugo -t crisp
  artifacts:
    paths:
    - public
  only:
  - master
