image: node:9

pages:
  script:
  - yarn
  - yarn add gatsby-cli
  - yarn build
  artifacts:
    paths:
    - public
  cache:
    paths:
    - node_modules
  only:
  - master

now:
  script:
  - npm install -g --unsafe-perm now
  - yarn run deploy-cif