image: node:9

pages:
  script:
  - npm install --unsafe-perm now
  - yarn && yarn run build
  artifacts:
    paths:
    - public
  cache:
    paths:
    - node_modules
    - .cache
    - public
  only:
  - master

now:
  script:
  - npm install --unsafe-perm now
  - yarn run deploy-ci
  artifacts:
    paths:
    - public
  cache:
    paths:
    - node_modules
    - .cache
    - public
  only:
  - master