# site settings
title: Victor Magalhães
subtitle: desenvolvedor front-end
email: victorhfmag@gmail.com
description: Desenvolvo web apps com React como ganha-pão, ainda acho o futuro é P2P, exagero no café e meio que sou de humanas
# description: Develops React-based web apps for a living, thinks blockchain & ML will take over the world, loves coffee and social justice.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vhfmag.gitlab.io" # the base hostname & protocol for your site
author: Victor Magalhães
street_address:
city: Salvador
state: BA
zip_code:
country: Brasil
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/vhfmag/
gitlab_url: https://gitlab.com/u/vhfmag
googleplus_url:
keybase_url: https://keybase.io/vhfmag
instagram_url: https://instagram.com/vhfmag
linkedin_url: https://www.linkedin.com/in/vhfmag
pinterest_url:
slack_url:
twitter_url: https://twitter.com/vhfmag

# build settings
markdown: kramdown

sass:
  style: compressed

# localization (polyglot gem)
languages: ["pt", "en", "fr"]
default_lang: "pt"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true

# let's encrypt
gitlab-letsencrypt:
  # Gitlab settings:
  personal_access_token: 'DCgztGMykGZ5nKQewL6y'    # Gotten from the step above ^^
  gitlab_repo:           'vhfmag/vhfmag.gitlab.io' # Namespaced repository identifier

  # Domain settings:
  email:                 'victorhfmag@gmail.com'     # Let's Encrypt email address
  domain:                'vhfmag.gitlab.io'             # Domain that the cert will be issued for

  # Jekyll settings:
  base_path:  ''                 # Where you want the file to go
  pretty_url: false              # Add a "/" on the end of the URL... set to `true` if you use permalink_style: pretty
  filename:   'letsencrypt.html' # What to call the generated challenge file

  # Delay settings:
  initial_delay: 120 # How long to wait for Gitlab CI to push your changes before it starts checking
  delay_time:     15 # How long to wait between each check once it starts looking for the file

  # Optional settings you probably don't need:
  # endpoint:  'https://somewhere' # if you're doing the ACME thing outside of letsencrypt
  branch:    'master'            # Defaults to master, but you can use a different branch
  layout:    'null'              # Layout to use for challenge file - defaults to null, but you can change if needed
  scheme:    'https'             # Scheme to use for challenge request; default http
