# site settings
title: Victor Magalhães
subtitle: desenvolvedor front-end
email: victorhfmag@gmail.com
description: Desenvolvo web apps baseados em React como profissão, acho que blockchain e ML vão dominar o mundo, exagero no café e meio que sou de humanas
# description: Develops React-based web apps for a living, thinks blockchain & ML will take over the world, loves coffee and social justice.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Victor Magalhães
street_address:
city: Salvador
state: BA
zip_code:
country: Brasil
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/vhfmag/
gitlab_url: https://gitlab.com/u/vhfmag
googleplus_url:
instagram_url: https://instagram.com/vhfmag
linkedin_url: https://www.linkedin.com/in/vhfmag
pinterest_url:
slack_url:
twitter_url: https://twitter.com/vhfmag

# build settings
markdown: kramdown

sass:
  style: compressed
