baseURL = "https://vhfmag.gitlab.io/"
languageCode = "pt-br"
title = "victor magalhães"
DefaultContentLanguage = "pt"
theme = "crisp"

[author]
name = "Victor Magalhães"
email = "victorhfmag@gmail.com"

[params]
# config
rss = true
index = "list"
tagline = "web dev, decent web & p2p enthusiast, into the solarpunk hype train"
# social
gravatarHash = "017c815c3972a18001cb840713ea761a"
keybase = "https://keybase.io/vhfmag"
linkedin = "https://www.linkedin.com/in/vhfmag"
github = "https://github.com/vhfmag/"
gitlab = "https://gitlab.com/vhfmag/"
twitter = "https://twitter.com/vhfmag"
pocket = "https://getpocket.com/@vhfmag"