baseURL = "https://vhfmag.netlify.com/"
languageCode = "pt-br"
title = "victor magalhães"
DefaultContentLanguage = "pt"
theme = "crisp"
Paginate = 5

[author]
name = "Victor Magalhães"
email = "vhfmag@protonmail.com"
birthplace = "Salvador, Bahia, Brazil"
birthdate = "1994-03-26"
jobtitle = "Web developer"
gender = "male"
nationality = "Brazil"
[author.address]
city = "Salvador"
province = "Bahia"
country = "Brazil"

[author.organization]
name = "Cubos"
url = "https://cubos.io/"
logo = "https://cubos.io/img/logo.svg"
phone = "+55 71 98788-3183"
[author.organization.address]
city = "Salvador"
street = "Alameda Salvador, 1057, Salvador Shopping Business, Torre América, Sala 1008"
postalcode = "41820-790"
province = "Bahia"
country = "Brazil"
map = "https://goo.gl/maps/HFMPxrhNeV92"
latitude = -12.97757
longitude = -38.4595287
# Salvador Shopping Business, Torre América, sala 1008 - Caminho das Árvores, Salvador - BA, 41820-790

[params]
# config
rss = true
index = "list"
tagline = "web dev, decent web & p2p enthusiast, into the solarpunk hype train"
# social
gravatarHash = "017c815c3972a18001cb840713ea761a"
keybase = "https://keybase.io/vhfmag"
linkedin = "https://www.linkedin.com/in/vhfmag"
github = "https://github.com/vhfmag/"
gitlab = "https://gitlab.com/vhfmag/"
twitter = "https://twitter.com/vhfmag"
instagram = "https://instagram.com/vhfmag"
pocket = "https://getpocket.com/@vhfmag"