version: 2
jobs:
    build:
        filters:
            branches:
                only:
                    - master
        docker:
            - image: circleci/node:8-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                  name: install dependencies and build website
                  command: |
                      npm install
                      npm run build
            - run:
                  name: run tests
                  command: npx percy snapshot public --ignore-files "/bookmarks/**"
