version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                  name: install dependencies
                  command: |
                      npm install

            - run:
                  name: run tests
                  command: |
                      npm run build
                      npx percy snapshot public --ignore-files "/bookmarks/**"
