version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                  name: install dependencies and build website
                  command: |
                      npm install
                      npm run build
    test:
        docker:
            - image: percyio/agent
        steps:
            - run:
                  name: run tests
                  command: npx percy snapshot public --ignore-files "/bookmarks/**"

workflows:
    build-and-test:
        jobs:
            - build:
                  filters:
                      branches:
                          only:
                              - master
            - test:
                  requires:
                      - build
