backend:
    name: gitlab
    repo: vhfmag/vhfmag.gitlab.io

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "img"

collections:
    - name: "bookmark"
      label: "Bookmark"
      folder: "src/content/bookmarks"
      extension: "mdx"
      format: "yaml-frontmatter"
      create: true
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Link", name: "link", widget: "string", required: false }
          - { label: "Draft", name: "draft", widget: "boolean", required: false }
          - { label: "Publish Date", name: "date", widget: "date" }
          - { label: "Tags", name: "tags", widget: "list", required: false }
          - label: "Authors"
            name: "authors"
            widget: "list"
            fields:
                - label: "Name"
                  name: "name"
                  widget: "string"
                - label: "URL"
                  name: "url"
                  widget: "string"
          - { label: "Body", name: "body", widget: "markdown", required: false }
